### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by joshrowley** [pathable/supermodel#63]
Hey, great project here. I started building a similar tool, but then found this project. Made keeping multiple views in sync a breeze. Is this published to NPM? Right now I'm using the latest commit SHA in my `package.json`, but it would be nice to take advantage of versioning through npm.

**Comment by lvv83** [comment]
Was published [here](https://www.npmjs.com/package/backbone.supermodel.js)

**Comment by joshrowley** [comment]
cool thanks 👍
